# Experiment-5

In [31]:
import numpy as np

In [32]:
x = np.array([
    [1, 0, 1, 1],
    [0, 0, 0, 1],
    [1, 0, 0, 1],
    [1, 1, 1, 0]
])

In [33]:
w = np.array([
    [0.9, 0.3, 0.1, 0.2],
    [0.1, 0.6, 0.2, 0.1]
])

In [34]:
lr = 0.1

In [35]:
epochs = 1
for e in range(epochs):
    print(f"\n---- Epoch {e+1} ----")
    print(f"Learning Rate: ",lr)
    for i in range(len(x)):
        print(f"\nInput {i+1}: {x[i]}")

        distances = ((w - x[i])**2).sum(axis=1)

        bmu = np.argmin(distances)

        print("Distances:",distances)
        print("BMU:",bmu+1)

        w[bmu] = w[bmu] + lr*(x[i] - w[bmu])

        print("Updated Weights:\n",w)

    lr *= 0.5


---- Epoch 1 ----
Learning Rate:  0.1

Input 1: [1 0 1 1]
Distances: [1.55 2.62]
BMU: 1
Updated Weights:
 [[0.91 0.27 0.19 0.28]
 [0.1  0.6  0.2  0.1 ]]

Input 2: [0 0 0 1]
Distances: [1.4555 1.22  ]
BMU: 2
Updated Weights:
 [[0.91 0.27 0.19 0.28]
 [0.09 0.54 0.18 0.19]]

Input 3: [1 0 0 1]
Distances: [0.6355 1.8082]
BMU: 1
Updated Weights:
 [[0.919 0.243 0.171 0.352]
 [0.09  0.54  0.18  0.19 ]]

Input 4: [1 1 1 0]
Distances: [1.390755 1.7482  ]
BMU: 1
Updated Weights:
 [[0.9271 0.3187 0.2539 0.3168]
 [0.09   0.54   0.18   0.19  ]]
